import type { AppData, Contract, MonthlyCharge, Property, Unit } from "@/types";
const now = "2026-04-01T00:00:00.000Z",
  uid = "";
const property = (
  id: string,
  code: string,
  name: string,
  type: string,
  address: string,
  date: string,
  price: number,
  costs: number,
  development: number,
  valuation: number,
  tax: number,
): Property => ({
  id,
  user_id: uid,
  property_code: code,
  name,
  property_type: type,
  address,
  acquisition_date: date,
  acquisition_price: price,
  acquisition_costs: costs,
  development_costs: development,
  current_valuation: valuation,
  remaining_debt: 0,
  annual_property_tax: tax,
  notes: "",
  created_at: now,
  updated_at: now,
});
const properties = [
  property(
    "p1",
    "P001",
    "市沢資材置き場",
    "資材置き場",
    "横浜市旭区",
    "2023-04-01",
    3200000,
    200000,
    500000,
    4500000,
    80000,
  ),
  property(
    "p2",
    "P002",
    "大和資材置き場",
    "資材置き場",
    "大和市",
    "2024-03-01",
    5000000,
    300000,
    700000,
    6500000,
    120000,
  ),
  property(
    "p3",
    "P003",
    "相模原貸地",
    "貸地",
    "相模原市",
    "2024-07-01",
    3800000,
    300000,
    700000,
    4000000,
    170000,
  ),
];
const unit = (
  id: string,
  pid: string,
  code: string,
  name: string,
  area: number,
  cars: number,
  power: boolean,
  rent: number,
): Unit => ({
  id,
  user_id: uid,
  property_id: pid,
  unit_code: code,
  name,
  usage_type: "資材置き場",
  area_sqm: area,
  vehicle_capacity: cars,
  has_power: power,
  heavy_machinery_allowed: true,
  standard_rent: rent,
  status: "稼働",
  notes: "",
  created_at: now,
  updated_at: now,
});
const units = [
  unit("u1", "p1", "A001", "市沢1区画", 80, 2, true, 30000),
  unit("u2", "p1", "A002", "市沢2区画", 90, 3, false, 32000),
  unit("u3", "p2", "B001", "大和1区画", 120, 4, true, 30000),
];
const contract = (
  id: string,
  code: string,
  pid: string,
  unitId: string,
  tenant: string,
  start: string,
  end: string | null,
  rent: number,
  type: "継続" | "定期",
  status: "契約中" | "終了予定",
): Contract => ({
  id,
  user_id: uid,
  contract_code: code,
  property_id: pid,
  unit_id: unitId,
  tenant_name: tenant,
  tenant_phone: null,
  tenant_email: null,
  tenant_address: null,
  start_date: start,
  end_date: end,
  monthly_rent: rent,
  billing_day: 1,
  payment_due_day: 末日(),
  contract_type: type,
  status,
  deposit_amount: 0,
  renewal_date: null,
  renewal_method: "",
  auto_renew: false,
  requires_recontract: false,
  renewal_cycle_months: null,
  renewal_fee: 0,
  guarantor_enabled: false,
  guarantor_company_name: "",
  guarantor_contract_number: "",
  guarantor_start_date: null,
  guarantor_end_date: null,
  guarantor_renewal_date: null,
  guarantor_fee: 0,
  guarantor_notes: "",
  bank_name: "",
  bank_branch: "",
  bank_account_type: "",
  bank_account_number: "",
  bank_account_holder: "",
  transfer_name: "",
  cancellation_notice_date: null,
  cancellation_planned_date: null,
  cancellation_completed_date: null,
  restoration_cost: 0,
  deposit_refund: 0,
  cancellation_notes: "",
  notes: "",
  created_at: now,
  updated_at: now,
});
function 末日() {
  return 31;
}
const contracts = [
  contract(
    "c1",
    "C001",
    "p1",
    "u1",
    "借主A",
    "2026-01-01",
    null,
    30000,
    "継続",
    "契約中",
  ),
  contract(
    "c2",
    "C002",
    "p1",
    "u2",
    "借主B",
    "2026-02-01",
    "2026-08-31",
    32000,
    "定期",
    "終了予定",
  ),
  contract(
    "c3",
    "C003",
    "p2",
    "u3",
    "借主C",
    "2026-04-01",
    null,
    30000,
    "継続",
    "契約中",
  ),
];
const charges: MonthlyCharge[] = contracts.map((c, i) => ({
  id: `ch${i + 1}`,
  user_id: uid,
  billing_month: "2026-04-01",
  property_id: c.property_id,
  unit_id: c.unit_id,
  contract_id: c.id,
  billed_amount: c.monthly_rent,
  paid_amount: c.monthly_rent,
  payment_date: "2026-04-01",
  payment_status: "入金済",
  memo: "",
  created_at: now,
  updated_at: now,
}));
export const demoData: AppData = {
  properties,
  units,
  contracts,
  charges,
  settings: {
    target_year: 2026,
    prorate_enabled: false,
    default_billing_day: 1,
    default_payment_due_day: 31,
    operation_start_date: null,
    opening_total_billed: 0,
    opening_total_paid: 0,
    opening_balance_through_date: null,
  },
  purchaseCandidates: [],
  purchaseAssumptions: {
    propertyTaxRate: 0.014,
    cityPlanningTaxRate: 0.003,
    landAcquisitionBaseRate: 0.5,
    landAcquisitionTaxRate: 0.03,
    buildingAcquisitionTaxRate: 0.04,
    landRegistrationTaxRate: 0.015,
    buildingRegistrationTaxRate: 0.02,
  },
  tasks: [],
  reminders: [],
  attachments: [],
};
