create table public.purchase_candidates (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), name text not null,
 purchase_price bigint not null default 0 check(purchase_price>=0), acquisition_costs bigint not null default 0 check(acquisition_costs>=0), land_valuation bigint not null default 0 check(land_valuation>=0), building_valuation bigint not null default 0 check(building_valuation>=0), renovation_costs bigint not null default 0 check(renovation_costs>=0), ten_year_repairs bigint not null default 0 check(ten_year_repairs>=0), expected_monthly_rent bigint not null default 0 check(expected_monthly_rent>=0), actual_monthly_rent bigint not null default 0 check(actual_monthly_rent>=0), vacancy_rate numeric not null default 0 check(vacancy_rate between 0 and 1), immediate_sale_price bigint not null default 0 check(immediate_sale_price>=0), holding_years integer not null default 10 check(holding_years between 1 and 50), future_sale_price bigint not null default 0 check(future_sale_price>=0), loan_amount bigint not null default 0 check(loan_amount>=0), interest_rate numeric not null default 0 check(interest_rate>=0), loan_years integer not null default 20 check(loan_years between 1 and 50), annual_operating_costs bigint not null default 0 check(annual_operating_costs>=0), notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.purchase_assumptions (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id), property_tax_rate numeric not null default .014, city_planning_tax_rate numeric not null default .003, land_acquisition_base_rate numeric not null default .5, land_acquisition_tax_rate numeric not null default .03, building_acquisition_tax_rate numeric not null default .04, land_registration_tax_rate numeric not null default .015, building_registration_tax_rate numeric not null default .02, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create trigger set_updated_at before update on public.purchase_candidates for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.purchase_assumptions for each row execute function public.set_updated_at();
alter table public.purchase_candidates enable row level security; alter table public.purchase_assumptions enable row level security;
create policy "own purchase candidates" on public.purchase_candidates for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own purchase assumptions" on public.purchase_assumptions for all using(user_id=auth.uid()) with check(user_id=auth.uid());
